class/urls.py
from django.urls import path
from .views import *
from . import views
app_name= 'class'
urlpatterns = [
    path('', DisplayClass.as_view(), name='display_class')

]

enroll/urls.py
from django.urls import path
from .views import *
from . import views
app_name= 'enroll'
urlpatterns = [
    path('', EnrollView.as_view(), name='enroll'),
    path('1', EnrollView2.as_view(), name='index'),
    path('thanks/', views.ThanksView, name='thanks')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('enroll/', include('enroll.urls')),
    path('class/', include('class.urls')),
    path('services/', include('services.urls')),

]

templates/homepage/base.html
{%load static%}

<html lang="en">
<head>
    {%block title%}


    {%endblock%}

    {%block meta%}

    {%endblock%}


    <!--    CSS     -->

    {% block cssblock%}
    {%endblock%}
    {%include 'homepage/navbar.html'%}

    <!--    END CSS     -->
</head>
<body>
<div class="warpper">
    <section class="ftco-section">
        <div class="wrap">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col">
                        <p class="mb-0 phone"><span class="fa fa-phone"></span> <a href="#">079 7903 136 (Th.Tôn) | 079
                            4374 992 (Thương)</a></p>
                    </div>
                    <div class="col d-flex justify-content-end">
                        <div class="social-media">
                            <p class="mb-0 d-flex">
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Somename <span>Gia Sư</span></a>
                <!--                <form action="#" class="searchform order-sm-start order-lg-last" >-->
                <!--                    <div class="form-group d-flex" >-->
                <!--                        <input type="text" class="form-control pl-3" placeholder="Search">-->
                <!--                        <button type="submit" placeholder="" class="form-control search"><span-->
                <!--                                class="fa fa-search"></span>-->
                <!--                        </button>-->
                <!--                    </div>-->
                <!--                </form>-->

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>

                <div class="order-sm-start order-lg-last">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a href="#"><i class="fa fa-phone"></i> 079 437 4992</a>
                        </li>
                    </ul>

                </div>
                <div class="collapse navbar-collapse" id="ftco-nav">

                    <ul class="navbar-nav m-auto">
                        <li class="nav-item active"><a href="{%url 'main:index'%}" class="nav-link">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="{%url 'class:display_class'%}" id="dropdown04"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">Lớp học</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="{%url 'class:display_class'%}">Lớp hiện có</a>

                            </div>
                        </li>
                        <li class="nav-item"><a href="{%url 'enroll:enroll'%}" class="nav-link">Đăng kí học</a>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Tin Tức</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Liên Hệ</a></li>
                    </ul>

                </div>

            </div>
        </nav>
        <!-- END nav -->
    </section>

    <div claas="container">
        <div class="row">
        <div class="col-2">

        </div>
        <div class="col-8">


            {% block content%}
            {%endblock%}

        </div>
        <div class="col-2">

        </div>


    </div>
    </div>

</div>
{%include 'homepage/footer.html'%}
<script src="{% static 'enroll/js/popper.js' %}"></script>
<script src="{% static 'enroll/js/bootstrap.min.js'%}"></script>
<script src="{% static 'enroll/js/main.js'%}"></script>
{% block jsblock%}
{%endblock%}
</body>
</html>

templates/homepage/footer.html
{%block footercss%}
<style>
     @import url('https://fonts.googleapis.com/css?family=Rubik&display=swap');


 .container-fluid {


     overflow: hidden;
     margin-top: 250px;
     background: #262626;
     color: #627482 !important;
     margin-bottom: 0;
     padding-bottom: 0
 }

 .footer-link{
    color: #627482 !important;
 }
 small {
     font-size: calc(12px + (15 - 12) * ((100vw - 360px) / (1600 - 360))) !important
 }

 .bold-text {
     color: #f2bc31 !important;
 }

 .mt-55 {
     margin-top: calc(50px + (60 - 50) * ((100vw - 360px) / (1600 - 360))) !important
 }

 .social {
     font-size: 21px !important
 }

 .rights {
     font-size: calc(10px + (12 - 10) * ((100vw - 360px) / (1600 - 360))) !important
 }
</style>
{%endblock%}

{%block footer%}
 <div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
     <footer>
         <div class="row my-5 justify-content-center py-5">
             <div class="col-11">
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                         <h3 class="text-muted mb-md-0 mb-5 bold-text">Tên</h3>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6>
                         <ul class="list-unstyled">
                             <li><a href="{%url 'main:index'%}" class="footer-link">HOME</a></li>
                             <li><a href="{%url 'class:display_class'%}" class="footer-link">LỚP HỌC</a></li>
                             <li><a href="{%url 'enroll:enroll'%}" class="footer-link">ĐĂNG KÍ HỌC</a></li>
                             <li><a href="{%url 'main:index'%}" class="footer-link">LIÊN HỆ</a></li>
                         </ul>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>ADDRESS</b></h6>
                         <p class="mb-1">KHU DÂN CƯ GIA HÒA</p>
                         <p>THÀNH PHỐ THỦ ĐỨC</p>
                     </div>
                 </div>
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                         <p class="social text-muted mb-0 pb-0 bold-text"> <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> </p><small class="rights"><span>&#174;</span> Thuong All Rights Reserved.</small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                         <h6 class="mt-55 mt-2 text-muted bold-text"><b>HOÀNG THHƯƠNG</b></h6><small> <span><i class="fa fa-envelope" aria-hidden="true"></i></span> n.h.thuong1701@gmail.com</small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3 ">
                         <h6 class="text-muted bold-text"><b>PH.D MINH TÔN</b></h6><small><span><i class="fa fa-envelope" aria-hidden="true"></i></span> minhton@gmail.com</small>
                     </div>
                 </div>
             </div>
         </div>
     </footer>
 </div>
{%endblock%}

templates/homepage/index.html
{%extends 'base.html'%}
{%load static%}
{%block header2%}
<!-- slider_area_start -->
<div class="slider_area ">
    <div class="single_slider d-flex align-items-center justify-content-center slider_bg_1">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-xl-6 col-md-6">
                    <div class="illastrator_png">
                        <img src="{% static 'img/banner/edu_ilastration.png' %}" alt="">
                    </div>
                </div>
                <div class="col-xl-6 col-md-6">
                    <div class="slider_info">
                        <h3>Learn your <br>
                            Favorite Course <br>
                            From Online</h3>
                        <a href="#" class="boxed_btn">Browse Our Courses</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider_area_end -->
{%endblock%}
{%block content%}
<div class="about-area">
    <h1>Content block</h1>
</div>

{%endblock%}

templates/homepage/navbar.html
{%load static%}
{% block navbarcss%}
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="{% static 'enroll/css/style.css' %}">
{%endblock%}


{% block jsblock %}
<script src="{% static 'enroll/js/jquery.min.js' %}"></script>
<script src="{% static 'enroll/js/popper.js' %}"></script>
<script src="{% static 'enroll/js/bootstrap.min.js' %}"></script>
<script src="{% static 'enroll/js/main.js' %}"></script>
{%endblock%}