class/urls.py
from django.urls import path
from .views import *
from . import views
app_name= 'class'
urlpatterns = [
    path('', DisplayClass.as_view(), name='display_class')

]

enroll/urls.py
from django.urls import path
from .views import *
from . import views
app_name= 'enroll'
urlpatterns = [
    path('', EnrollView.as_view(), name='enroll'),
    path('1', EnrollView2.as_view(), name='index'),
    path('thanks/', views.ThanksView, name='thanks')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('enroll/', include('enroll.urls')),
    path('class/', include('class.urls')),
    path('services/', include('services.urls')),

]

enroll/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone


# -----------Text Choices-----------
class Sex(models.TextChoices):
    __empty__ = _('Yêu cầu về giới tính người dạy')
    MALE = 'Nam', _('Nam')
    FEMALE = 'Nữ', _('Nữ')
    BOTH = 'Khác', _('Khác')


class Districts(models.TextChoices):
    __empty__ = _('Quận/Huyện')
    District_1 = 'Quận 1', _('Quận 1')
    District_2 = 'Quận 2', _('Quận 2')
    District_3 = 'Quận 3', _('Quận 3')
    District_4 = 'Quận 4', _('Quận 4')

    District_5 = 'Quận 5', _('Quận 5')
    District_6 = 'Quận 6', _('Quận 6')
    District_7 = 'Quận 7', _('Quận 7')
    District_8 = 'Quận 8', _('Quận 8')
    District_9 = 'Quận 9', _('Quận 9')

    District_10 = 'Quận 10', _('Quận 10')
    District_11 = 'Quận 11', _('Quận 11')
    District_12 = 'Quận 12', _('Quận 12')
    BinhChanh_District = 'Bình Chánh', _('Bình Chánh')

    BinhTan_District = 'BTan', _('Bình Tân')
    BinhThanh_District = 'BThanh', _('Bình Thạnh')
    CanGio_District = 'CG', _('Cần Giờ ')
    CuChi_District = 'CC', _('Củ Chi')

    HocMon_District = 'HM', _('Hóc Môn')
    NhaBe_District = 'NB', _('Nhà Bè')
    PhuNhuan_District = 'PN', _('Phú Nhuận')
    TanPhu_District = 'TP', _('Tân Phú')

    TanBinh_District = 'TB', _('Tân Bình')
    ThuDuc_District = 'TD', _('Thủ Đức')


class StudentLevel(models.TextChoices):
    __empty__ = _('Chương trình học mong muốn')
    TIEUHOC = 'tieuhoc', _('Chương trình Tiểu học')
    THCS = 'thcs', _('Chương trình Trung Học Cơ Sở')
    THPT = 'thpt', _('Chương trình Trung Học Phổ Thông')

    CT_QUOCTE = 'ct_quocte', _('Chương trình Quốc Tế')
    # Giang day
    GD_TIENGANH = 'gd_tienganh', _('DẠY BẰNG TIẾNG ANH CÁC MÔN TOÁN-LÝ-HÓA ')
    GD_CANBAN = 'gd_canban', _('DẠY CĂN BẢN CÁC MÔN TOÁN-LÝ-HÓA')

    LT_SAT = 'lt_sat', _('LUYỆN THI SAT')
    LT_TRANDAINGHIA = 'lt_trandainghia', _('LUYỆN THI VÀO LỚP 6 TRẦN ĐẠI NGHĨA')
    LT_LOP10 = 'lt_lop10', _('LUYỆN THI VÀO LỚP 10 TRƯỜNG CHUYÊN / CÔNG LẬP')
    LT_DAIHOC = 'lt_daihoc', _('LUYỆN THI ĐẠI HỌC')

    IELTS = 'ielts', _('IELTS Cơ bản')

    KHAC = 'khac', _('Khác')


# -----------END Text Choices-----------


# -----------Model-----------

class ClassInfo(models.Model):
    class_id = models.AutoField(primary_key=True)
    name = models.CharField('Họ và tên', max_length=100, blank=False)
    phone_number = models.CharField('Số điện thoại', max_length=12, blank=False, default='')
    email = models.EmailField('Địa chỉ Email', max_length=254, blank=True, default='')
    district = models.CharField('Tên quận', max_length=10, choices=Districts.choices, blank=False)
    address = models.CharField('Địa chỉ', max_length=200, blank=True, default='')
    subjects = models.CharField('Môn học', max_length=100, blank=True, default='')
    student_info = models.CharField('Thông tin học sinh', default='', blank = True , max_length=255)
    num_student = models.PositiveIntegerField('Số lượng học sinh', blank=True, default=0, null=True)
    date_start = models.DateField('Ngày khai giảng', blank=True, null=True, default='')
    lop = models.CharField('Lớp', max_length=10, default='')
    #level = models.CharField('Level', max_length=26, choices=StudentLevel.choices)
    fee_expected = models.IntegerField('Mức lương', blank=True, default=0, null=True)
    frequency = models.PositiveIntegerField('Số buổi/Tuần', default=2, blank=True, null=True)
    teaching_time = models.CharField('Thời gian dạy', max_length=500, blank=True, help_text='VD: Tối 2-4-6, 18h',
                                     default='')
    sex_require = models.CharField('Yêu cầu về giới tính', max_length=10, choices=Sex.choices)
    # ----- after this line,add more field must require option default
    note = models.TextField('Ghi chú', default='', blank=True)
    status = models.BooleanField('Trạng Thái lớp', default=False , help_text=('Đang dạy(tick)/Ngưng dạy(untick)'))
    confirmed = models.BooleanField('Đã xác nhận', default=False, help_text=('Đã xác nhận với phụ huynh ? '))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} - {self.phone_number} - {self.district} - {self.status}'

enroll/forms.py
from django import forms
from .models import ClassInfo
class EnrollForm(forms.ModelForm):
    class Meta:
        model = ClassInfo
        fields = [
            'name' , 'phone_number', 'district',
            'address', 'email', 'subjects', 'lop',
            'num_student', 'date_start' , 'fee_expected',
            'frequency', 'teaching_time', 'sex_require',
            'note'
        ]
        widgets = {
            'date_start': forms.DateInput(attrs={'type':'date'}),
            'note' : forms.Textarea(attrs={'class':'input--style-1', 'cols':'60', 'rows':'5'})
        }

enroll/views.py
from django.shortcuts import render
from django.views.generic import View , FormView
from .forms import EnrollForm
from .models import ClassInfo
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.


class EnrollView(FormView):

    def get(self, request):
        form = EnrollForm()
        context = {'f': form, 'c': 'active'}
        template = 'enroll/index.html'
        return render(request, template,context)
    def post(self, request):
        form = EnrollForm(request.POST)
        context = {'f': form, 'c': 'active'}
        if form.is_valid():
            data = form.cleaned_data
            request.session['name'] = data['name']

            instance = ClassInfo()
            f = EnrollForm(request.POST, instance=instance)

            f.save()
            return HttpResponseRedirect(reverse('enroll:thanks'))
        else:
            return render(request, 'enroll/index.html', context)
class EnrollView2(View):
    def get(self, request):
        context = {'enroll_active': 'active'}
        template = 'enroll/index2.html'
        return render(request, template, context)


def ThanksView(request):
    if request.session.get('name'):
        template_name= 'enroll/thanks.html'
        name = request.session['name']
        del request.session['name'] #delete session after used it
        return render(request, template_name , {'name': name})
    else:
        return HttpResponseRedirect(reverse('enroll:enroll'))

templates/enroll/base_enroll.html
{%load static%}

<html lang="en">
<head>
    {%block title%}
    {%endblock%}


    {%block meta%}
    {%endblock%}


    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">





    {% block cssblock%}
    {%endblock%}
    <link href="{% static 'enroll/css/style.css'%}" rel="stylesheet" media="all">

</head>
<body>

<div class="warpper">
    <section class="ftco-section">
        <div class="wrap">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col">
                        <p class="mb-0 phone"><span class="fa fa-phone"></span> <a href="#">079 7903 136 (Th.Tôn) | 079
                            4374 992 (Thương)</a></p>
                    </div>
                    <div class="col d-flex justify-content-end">
                        <div class="social-media">
                            <p class="mb-0 d-flex">
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-facebook"><i class="sr-only">Facebook</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-twitter"><i class="sr-only">Twitter</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-instagram"><i class="sr-only">Instagram</i></span></a>
                                <a href="#" class="d-flex align-items-center justify-content-center"><span
                                        class="fa fa-dribbble"><i class="sr-only">Dribbble</i></span></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">Somename <span>Gia Sư</span></a>
                <!--                <form action="#" class="searchform order-sm-start order-lg-last" >-->
                <!--                    <div class="form-group d-flex" >-->
                <!--                        <input type="text" class="form-control pl-3" placeholder="Search">-->
                <!--                        <button type="submit" placeholder="" class="form-control search"><span-->
                <!--                                class="fa fa-search"></span>-->
                <!--                        </button>-->
                <!--                    </div>-->
                <!--                </form>-->

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>

                <div class="order-sm-start order-lg-last">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a href="#"><i class="fa fa-phone"></i> 079 437 4992</a>
                        </li>
                    </ul>

                </div>
                <div class="collapse navbar-collapse" id="ftco-nav">

                    <ul class="navbar-nav m-auto">
                        <li class="nav-item {{a}}"><a href="{%url 'main:index'%}" class="nav-link">Home</a></li>
                        <li class="nav-item dropdown {{b}}">
                            <a class="nav-link dropdown-toggle" href="{%url 'class:display_class'%}" id="dropdown04" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">Lớp học</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                 <a class="dropdown-item" href="{%url 'class:display_class'%}">Lớp hiện có</a>

                            </div>
                        </li>
                        <li class="nav-item {{c}}"><a href="{%url 'enroll:enroll'%}" class="nav-link">Đăng kí học</a>
                        </li>
                        <li class="nav-item {{d}}"><a href="#" class="nav-link">Tin Tức</a></li>
                        <li class="nav-item {{e}}"><a href="#" class="nav-link">Liên Hệ</a></li>
                    </ul>

                </div>

            </div>
        </nav>
        <!-- END nav -->
    </section>
    <div class="container">
        <div class="row">
        <div class="col-10">


            {% block content%}
            {%endblock%}
            {% block content_class%}
            {%endblock%}
        </div>
        <div class="col">

        </div>


    </div>
    </div>

</div>
{%include 'homepage/footer.html'%}
<script src="{% static 'enroll/js/jquery.min.js' %}"></script>

<script src="{% static 'enroll/js/popper.js' %}"></script>
<script src="{% static 'enroll/js/bootstrap.min.js'%}"></script>
<script src="{% static 'enroll/vendor/jquery/jquery.min.js'%}"></script>
<!-- Main JS-->
<script src="{%static 'enroll/js/global.js'%}"></script>
<script src="{%static 'enroll/js/main.js'%}"></script>
{% block jsblock%}
{%endblock%}
</body>
</html>

templates/enroll/index.html
{%extends 'enroll/base_enroll.html'%}
{%load static%}

<!-- Required meta tags-->
{%block meta%}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% endblock %}


{%block title %}<title>GHI DANH</title> {%endblock%}


{% block cssblock%}
<!-- Icons font CSS-->
<link href="{% static 'enroll/vendor/mdi-font/css/material-design-iconic-font.min.css'%}" rel="stylesheet"
      media="all">
<link href="{% static 'enroll/vendor/font-awesome-4.7/css/font-awesome.min.css'%}" rel="stylesheet" media="all">
<!-- Font special for pages-->
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i"
      rel="stylesheet">
<!-- Vendor CSS-->
<link href="{% static 'enroll/vendor/select2/select2.min.css'%}" rel="stylesheet" media="all">
<!-- Main CSS-->
<link href="{% static 'enroll/css/style.css'%}" rel="stylesheet" media="all">
{%endblock%}

{%block content%}
<!--    <div class="page-wrapper bg-blue p-t-100 p-b-100 font-robo">-->
<!--        <div class="wrapper wrapper&#45;&#45;w680">-->
<div class="card card-1">
    <div class="card-body">

        <form method="POST">

            {% csrf_token %}
            <h3 class="title">Thông Tin Liên Hệ</h3>
            <div class="font-italic"> (Vui lòng điền đầy đủ thông tin)</div>

            <div class="input-group">
                <input class="input&#45;&#45;style-1" type="text" placeholder="HỌ TÊN" name="name" required
                       id="id_name">
            </div>
            <div class="input-group">
                <input class="input--style-1" type="text" placeholder="SỐ ĐIỆN THOẠI" name="phone_number" required
                       id="id_phone_number">
            </div>
            <div class="input-group">
                <input class="input--style-1" type="text" placeholder="EMAIL" name="email" required id="id_email">
            </div>
            <div class="row row-space">


                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="TÊN ĐƯỜNG , PHƯỜNG" name="address"
                               id="id_address">
                    </div>

                </div>
                <div class="col">
                    <div class="input-group">
                        <div class="rs-select2 js-select-simple select--no-search">

                            {{f.district}}
                            <div class="select-dropdown"></div>
                        </div>
                    </div>
                </div>
            </div>
            <h3 class="title d-inline-flex">Thông tin khác</h3>
            <div class="font-italic"> (Không bắt buộc)</div>
            <div class="row row-space">
                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="LỚP" name="numstudent"
                               id="id_lop">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="MÔN HỌC" name="numstudent"
                               id="id_subjects">
                    </div>
                </div>
            </div>
            <div class="row row-space">
                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="SỐ LƯỢNG HỌC SINH" name="numstudent"
                               id="id_numstudent">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="SỐ BUỔI / TUẦN" name="frequency"
                               id="id_frequency" style="text-align:center;">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group">
                        <input class="input--style-1" type="text" placeholder="MỨC LƯƠNG " name="fee_expected"
                               id="id_fee_expected" style="text-align:center;">
                    </div>
                </div>
            </div>
            <div class="input-group">
                {{f.date_start}}
            </div>
            <div class="input-group">
                <div class="rs-select2 js-select-simple select--no-search ">

                    {{f.sex_require}}

                    <div class="select-dropdown"></div>
                </div>
            </div>
            <div class="input-group">
                <div class="rs-select2 js-select-simple select--no-search">
                    <select name="gender">
                        <option disabled="disabled" selected="selected">GENDER</option>
                        <option>Male</option>
                        <option>Female</option>
                        <option>Other</option>
                    </select>
                    <div class="select-dropdown"></div>
                </div>
            </div>
            <div class="input-group2">
                <p>GHI CHÚ</p>
                {{f.note}}
            </div>
            <div class="p-t-20">
                <button class="btn btn--radius btn--green" type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>

<!-- Jquery JS-->


{%endblock%}
{%block jsblock%}

<!-- Vendor JS-->
<script src="{%static 'enroll/vendor/select2/select2.min.js'%}"></script>
<!-- Main JS-->
<script src="{%static 'enroll/js/global.js'%}"></script>
{%endblock%}

<!-- end document-->

templates/enroll/index2.html
{%extends 'base.html'%}
{%load static%}

{%block title %}<title>GHI DANH</title> {%endblock%}

{%block header2%}
<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg overlay2">
    <h3>ĐĂNG KÝ HỌC</h3>
</div>
<!-- bradcam_area_end -->
{%endblock%}


{%block content%}

{%endblock%}

templates/enroll/thanks.html
{%extends 'enroll/base_enroll.html'%}

{%block title %}
<title>Thành Công !</title>
{%endblock%}


{%block content%}
<h1> Cảm ơn {{name}}, thông tin của bạn đã đươc ghi lại, chúng tôi sẽ liên hệ cho bạn sớm nhất có thể. </h1>
{% endblock%}
{%include 'homepage/footer.html'%}